// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: internal/model/testdata.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	String_        string                       `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	Int32          int32                        `protobuf:"varint,2,opt,name=int32,proto3" json:"int32,omitempty"`
	Bool           bool                         `protobuf:"varint,3,opt,name=bool,proto3" json:"bool,omitempty"`
	RepeatedString []string                     `protobuf:"bytes,4,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	NestedMessage  *TestMessage1_NestedMessage1 `protobuf:"bytes,5,opt,name=nested_message,json=nestedMessage,proto3" json:"nested_message,omitempty"`
	Timestamp      *timestamppb.Timestamp       `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TestMessage1) Reset() {
	*x = TestMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_testdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage1) ProtoMessage() {}

func (x *TestMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_testdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage1.ProtoReflect.Descriptor instead.
func (*TestMessage1) Descriptor() ([]byte, []int) {
	return file_internal_model_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage1) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *TestMessage1) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *TestMessage1) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *TestMessage1) GetRepeatedString() []string {
	if x != nil {
		return x.RepeatedString
	}
	return nil
}

func (x *TestMessage1) GetNestedMessage() *TestMessage1_NestedMessage1 {
	if x != nil {
		return x.NestedMessage
	}
	return nil
}

func (x *TestMessage1) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TestMessage1_NestedMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                 string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AnotherNestedMessage *TestMessage1_NestedMessage2 `protobuf:"bytes,2,opt,name=another_nested_message,json=anotherNestedMessage,proto3" json:"another_nested_message,omitempty"`
}

func (x *TestMessage1_NestedMessage1) Reset() {
	*x = TestMessage1_NestedMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_testdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage1_NestedMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage1_NestedMessage1) ProtoMessage() {}

func (x *TestMessage1_NestedMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_testdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage1_NestedMessage1.ProtoReflect.Descriptor instead.
func (*TestMessage1_NestedMessage1) Descriptor() ([]byte, []int) {
	return file_internal_model_testdata_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TestMessage1_NestedMessage1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMessage1_NestedMessage1) GetAnotherNestedMessage() *TestMessage1_NestedMessage2 {
	if x != nil {
		return x.AnotherNestedMessage
	}
	return nil
}

type TestMessage1_NestedMessage2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"zigzag32,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *TestMessage1_NestedMessage2) Reset() {
	*x = TestMessage1_NestedMessage2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_testdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage1_NestedMessage2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage1_NestedMessage2) ProtoMessage() {}

func (x *TestMessage1_NestedMessage2) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_testdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage1_NestedMessage2.ProtoReflect.Descriptor instead.
func (*TestMessage1_NestedMessage2) Descriptor() ([]byte, []int) {
	return file_internal_model_testdata_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TestMessage1_NestedMessage2) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_internal_model_testdata_proto protoreflect.FileDescriptor

var file_internal_model_testdata_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x96, 0x03, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x31, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62,
	0x6f, 0x6f, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x43, 0x0a, 0x0e,
	0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x31, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x31, 0x52, 0x0d, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x1a, 0x78, 0x0a, 0x0e, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x52, 0x0a, 0x16, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x6e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31,
	0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x52,
	0x14, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x22, 0x0a, 0x0e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x11, 0x52, 0x03, 0x69, 0x64, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_model_testdata_proto_rawDescOnce sync.Once
	file_internal_model_testdata_proto_rawDescData = file_internal_model_testdata_proto_rawDesc
)

func file_internal_model_testdata_proto_rawDescGZIP() []byte {
	file_internal_model_testdata_proto_rawDescOnce.Do(func() {
		file_internal_model_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_model_testdata_proto_rawDescData)
	})
	return file_internal_model_testdata_proto_rawDescData
}

var file_internal_model_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_model_testdata_proto_goTypes = []interface{}{
	(*TestMessage1)(nil),                // 0: TestMessage1
	(*TestMessage1_NestedMessage1)(nil), // 1: TestMessage1.NestedMessage1
	(*TestMessage1_NestedMessage2)(nil), // 2: TestMessage1.NestedMessage2
	(*timestamppb.Timestamp)(nil),       // 3: google.protobuf.Timestamp
}
var file_internal_model_testdata_proto_depIdxs = []int32{
	1, // 0: TestMessage1.nested_message:type_name -> TestMessage1.NestedMessage1
	3, // 1: TestMessage1.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: TestMessage1.NestedMessage1.another_nested_message:type_name -> TestMessage1.NestedMessage2
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_model_testdata_proto_init() }
func file_internal_model_testdata_proto_init() {
	if File_internal_model_testdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_model_testdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_model_testdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage1_NestedMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_model_testdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage1_NestedMessage2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_model_testdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_model_testdata_proto_goTypes,
		DependencyIndexes: file_internal_model_testdata_proto_depIdxs,
		MessageInfos:      file_internal_model_testdata_proto_msgTypes,
	}.Build()
	File_internal_model_testdata_proto = out.File
	file_internal_model_testdata_proto_rawDesc = nil
	file_internal_model_testdata_proto_goTypes = nil
	file_internal_model_testdata_proto_depIdxs = nil
}
