// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "server.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Server } from "./server";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CompileResponse } from "./server";
import type { CompileRequest } from "./server";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Server
 */
export interface IServerClient {
    /**
     * @generated from protobuf rpc: Compile(CompileRequest) returns (CompileResponse);
     */
    compile(input: CompileRequest, options?: RpcOptions): UnaryCall<CompileRequest, CompileResponse>;
}
/**
 * @generated from protobuf service Server
 */
export class ServerClient implements IServerClient, ServiceInfo {
    typeName = Server.typeName;
    methods = Server.methods;
    options = Server.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Compile(CompileRequest) returns (CompileResponse);
     */
    compile(input: CompileRequest, options?: RpcOptions): UnaryCall<CompileRequest, CompileResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CompileRequest, CompileResponse>("unary", this._transport, method, opt, input);
    }
}
