#!/bin/sh
set -e
cd "$(dirname "$0")/.."

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

# Kill background demo-app when the script exits
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

export GOBIN=$PWD/bin
export PATH=$GOBIN:$PATH

go build -o /tmp/demo-app ./cmd/demo-app
/tmp/demo-app &

# Stop and remove the container if it already exists
docker rm -f kaja-twirp-dev &> /dev/null || true

docker build . -t kaja-twirp-dev:latest

docker run --name kaja-twirp-dev -d -p 3000:3000 \
    -v $PWD/proto:/app/proto \
    -e BASE_URL="http://host.docker.internal:41521" --add-host=host.docker.internal:host-gateway kaja-twirp-dev:latest

# Open kaja-twirp in a default web browser
echo -e "${GREEN}Opening kaja-twirp URL http://localhost:3000/ in your default web browser${NC}"
python3 -m webbrowser http://localhost:3000/


cat