#!/bin/bash
set -e

cd "$(dirname "$0")/../demo"

# Kill background demo-app when the script exits
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

export GOBIN=$PWD/bin
export PATH=$GOBIN:$PATH
go install github.com/twitchtv/twirp/protoc-gen-twirp@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

go build -o /tmp/demo-app ./cmd/demo-app
/tmp/demo-app &

cd "../app"
rm -rf ./src/client/protoc
npm i
npm start