#!/bin/bash
set -e
cd "$(dirname "$0")/.."

PROTO_PATH="/Users/wham/github/billing-platform"
npx protoc --ts_out ./ui/src/gen --ts_opt long_type_string -I/Users/wham/github/billing-platform/ $(find /Users/wham/github/billing-platform -iname "*.proto")
(cd ./genpick && npm i && npm start)
(cd ./ui && npm i && npm start)