#!/bin/bash
set -e
cd "$(dirname "$0")/.."

(cd ./plugin && npm i && npm run build)
npx protoc --proto_path=./proto --plugin=protoc-gen-kaja-twirp=./plugin/bin/protoc-gen-kaja-twirp --kaja-twirp_out=./ui/src --ts_out ./ui/src --ts_opt long_type_string -Iproto/ $(find proto -iname "*.proto")
(cd ./ui && npm i && npm start)