#!/bin/bash
set -e
cd "$(dirname "$0")/.."

npx protoc --ts_out ./ui/src/gen --ts_opt long_type_string -I./proto $(find proto -iname "*.proto")
(cd ./genpick && npm i && npm start)
(cd ./ui && npm i && npm start)