// @generated by protobuf-ts 2.9.1 with parameter client_none,generate_dependencies
// @generated from protobuf file "api.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message BootstrapRequest
 */
export interface BootstrapRequest {
    /**
     * @generated from protobuf field: int32 log_offset = 1;
     */
    logOffset: number;
}
/**
 * @generated from protobuf message BootstrapResponse
 */
export interface BootstrapResponse {
    /**
     * @generated from protobuf field: BootstrapStatus status = 1;
     */
    status: BootstrapStatus;
    /**
     * @generated from protobuf field: repeated Log logs = 2;
     */
    logs: Log[];
}
/**
 * @generated from protobuf message Log
 */
export interface Log {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
    /**
     * @generated from protobuf field: int32 index = 2;
     */
    index: number;
    /**
     * @generated from protobuf field: LogLevel level = 3;
     */
    level: LogLevel;
}
/**
 * @generated from protobuf enum BootstrapStatus
 */
export enum BootstrapStatus {
    /**
     * @generated from protobuf enum value: STATUS_READY = 0;
     */
    STATUS_READY = 0,
    /**
     * @generated from protobuf enum value: STATUS_ERROR = 1;
     */
    STATUS_ERROR = 1,
    /**
     * @generated from protobuf enum value: STATUS_RUNNING = 2;
     */
    STATUS_RUNNING = 2
}
/**
 * @generated from protobuf enum LogLevel
 */
export enum LogLevel {
    /**
     * @generated from protobuf enum value: LEVEL_DEBUG = 0;
     */
    LEVEL_DEBUG = 0,
    /**
     * @generated from protobuf enum value: LEVEL_INFO = 1;
     */
    LEVEL_INFO = 1,
    /**
     * @generated from protobuf enum value: LEVEL_WARN = 2;
     */
    LEVEL_WARN = 2,
    /**
     * @generated from protobuf enum value: LEVEL_ERROR = 3;
     */
    LEVEL_ERROR = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class BootstrapRequest$Type extends MessageType<BootstrapRequest> {
    constructor() {
        super("BootstrapRequest", [
            { no: 1, name: "log_offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<BootstrapRequest>): BootstrapRequest {
        const message = { logOffset: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BootstrapRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BootstrapRequest): BootstrapRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 log_offset */ 1:
                    message.logOffset = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BootstrapRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 log_offset = 1; */
        if (message.logOffset !== 0)
            writer.tag(1, WireType.Varint).int32(message.logOffset);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BootstrapRequest
 */
export const BootstrapRequest = new BootstrapRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BootstrapResponse$Type extends MessageType<BootstrapResponse> {
    constructor() {
        super("BootstrapResponse", [
            { no: 1, name: "status", kind: "enum", T: () => ["BootstrapStatus", BootstrapStatus] },
            { no: 2, name: "logs", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Log }
        ]);
    }
    create(value?: PartialMessage<BootstrapResponse>): BootstrapResponse {
        const message = { status: 0, logs: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BootstrapResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BootstrapResponse): BootstrapResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* BootstrapStatus status */ 1:
                    message.status = reader.int32();
                    break;
                case /* repeated Log logs */ 2:
                    message.logs.push(Log.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BootstrapResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* BootstrapStatus status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).int32(message.status);
        /* repeated Log logs = 2; */
        for (let i = 0; i < message.logs.length; i++)
            Log.internalBinaryWrite(message.logs[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BootstrapResponse
 */
export const BootstrapResponse = new BootstrapResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Log$Type extends MessageType<Log> {
    constructor() {
        super("Log", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "index", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "level", kind: "enum", T: () => ["LogLevel", LogLevel] }
        ]);
    }
    create(value?: PartialMessage<Log>): Log {
        const message = { message: "", index: 0, level: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Log>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Log): Log {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* int32 index */ 2:
                    message.index = reader.int32();
                    break;
                case /* LogLevel level */ 3:
                    message.level = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Log, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* int32 index = 2; */
        if (message.index !== 0)
            writer.tag(2, WireType.Varint).int32(message.index);
        /* LogLevel level = 3; */
        if (message.level !== 0)
            writer.tag(3, WireType.Varint).int32(message.level);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Log
 */
export const Log = new Log$Type();
/**
 * @generated ServiceType for protobuf service Api
 */
export const Api = new ServiceType("Api", [
    { name: "Bootstrap", options: {}, I: BootstrapRequest, O: BootstrapResponse }
]);
